/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/sign-in'
import { Route as DefaultRouteImport } from './routes/_default/route'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexImport } from './routes/index'
import { Route as DefaultSupportRouteImport } from './routes/_default/support/route'
import { Route as DefaultHomepageRouteImport } from './routes/_default/homepage/route'
import { Route as DefaultGiftsRouteImport } from './routes/_default/gifts/route'
import { Route as DefaultCareerRouteImport } from './routes/_default/career/route'
import { Route as AuthenticatedUserRouteImport } from './routes/_authenticated/user/route'
import { Route as AuthenticatedSpecialistRouteImport } from './routes/_authenticated/specialist/route'

// Create/Update Routes

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const DefaultRouteRoute = DefaultRouteImport.update({
  id: '/_default',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DefaultSupportRouteRoute = DefaultSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const DefaultHomepageRouteRoute = DefaultHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const DefaultGiftsRouteRoute = DefaultGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const DefaultCareerRouteRoute = DefaultCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const AuthenticatedUserRouteRoute = AuthenticatedUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSpecialistRouteRoute =
  AuthenticatedSpecialistRouteImport.update({
    id: '/specialist',
    path: '/specialist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DefaultRouteImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/specialist': {
      id: '/_authenticated/specialist'
      path: '/specialist'
      fullPath: '/specialist'
      preLoaderRoute: typeof AuthenticatedSpecialistRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/user': {
      id: '/_authenticated/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthenticatedUserRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_default/career': {
      id: '/_default/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof DefaultCareerRouteImport
      parentRoute: typeof DefaultRouteImport
    }
    '/_default/gifts': {
      id: '/_default/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof DefaultGiftsRouteImport
      parentRoute: typeof DefaultRouteImport
    }
    '/_default/homepage': {
      id: '/_default/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof DefaultHomepageRouteImport
      parentRoute: typeof DefaultRouteImport
    }
    '/_default/support': {
      id: '/_default/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof DefaultSupportRouteImport
      parentRoute: typeof DefaultRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSpecialistRouteRoute: typeof AuthenticatedSpecialistRouteRoute
  AuthenticatedUserRouteRoute: typeof AuthenticatedUserRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSpecialistRouteRoute: AuthenticatedSpecialistRouteRoute,
  AuthenticatedUserRouteRoute: AuthenticatedUserRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DefaultRouteRouteChildren {
  DefaultCareerRouteRoute: typeof DefaultCareerRouteRoute
  DefaultGiftsRouteRoute: typeof DefaultGiftsRouteRoute
  DefaultHomepageRouteRoute: typeof DefaultHomepageRouteRoute
  DefaultSupportRouteRoute: typeof DefaultSupportRouteRoute
}

const DefaultRouteRouteChildren: DefaultRouteRouteChildren = {
  DefaultCareerRouteRoute: DefaultCareerRouteRoute,
  DefaultGiftsRouteRoute: DefaultGiftsRouteRoute,
  DefaultHomepageRouteRoute: DefaultHomepageRouteRoute,
  DefaultSupportRouteRoute: DefaultSupportRouteRoute,
}

const DefaultRouteRouteWithChildren = DefaultRouteRoute._addFileChildren(
  DefaultRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof DefaultRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/specialist': typeof AuthenticatedSpecialistRouteRoute
  '/user': typeof AuthenticatedUserRouteRoute
  '/career': typeof DefaultCareerRouteRoute
  '/gifts': typeof DefaultGiftsRouteRoute
  '/homepage': typeof DefaultHomepageRouteRoute
  '/support': typeof DefaultSupportRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof DefaultRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/specialist': typeof AuthenticatedSpecialistRouteRoute
  '/user': typeof AuthenticatedUserRouteRoute
  '/career': typeof DefaultCareerRouteRoute
  '/gifts': typeof DefaultGiftsRouteRoute
  '/homepage': typeof DefaultHomepageRouteRoute
  '/support': typeof DefaultSupportRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_default': typeof DefaultRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/specialist': typeof AuthenticatedSpecialistRouteRoute
  '/_authenticated/user': typeof AuthenticatedUserRouteRoute
  '/_default/career': typeof DefaultCareerRouteRoute
  '/_default/gifts': typeof DefaultGiftsRouteRoute
  '/_default/homepage': typeof DefaultHomepageRouteRoute
  '/_default/support': typeof DefaultSupportRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/sign-in'
    | '/specialist'
    | '/user'
    | '/career'
    | '/gifts'
    | '/homepage'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/sign-in'
    | '/specialist'
    | '/user'
    | '/career'
    | '/gifts'
    | '/homepage'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_default'
    | '/sign-in'
    | '/_authenticated/specialist'
    | '/_authenticated/user'
    | '/_default/career'
    | '/_default/gifts'
    | '/_default/homepage'
    | '/_default/support'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DefaultRouteRoute: typeof DefaultRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DefaultRouteRoute: DefaultRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/_default",
        "/sign-in"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/specialist",
        "/_authenticated/user"
      ]
    },
    "/_default": {
      "filePath": "_default/route.tsx",
      "children": [
        "/_default/career",
        "/_default/gifts",
        "/_default/homepage",
        "/_default/support"
      ]
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/_authenticated/specialist": {
      "filePath": "_authenticated/specialist/route.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/user": {
      "filePath": "_authenticated/user/route.tsx",
      "parent": "/_authenticated"
    },
    "/_default/career": {
      "filePath": "_default/career/route.tsx",
      "parent": "/_default"
    },
    "/_default/gifts": {
      "filePath": "_default/gifts/route.tsx",
      "parent": "/_default"
    },
    "/_default/homepage": {
      "filePath": "_default/homepage/route.tsx",
      "parent": "/_default"
    },
    "/_default/support": {
      "filePath": "_default/support/route.tsx",
      "parent": "/_default"
    }
  }
}
ROUTE_MANIFEST_END */
